[workspace]
resolver = "2"
members = [
  "lightyear",
  "macros",
  # internal
  "benches",
  "examples/*",
]
default-members = ["lightyear"]
exclude = ["examples/certificates"]

[patch.crates-io]
steamworks = { git = "https://github.com/Noxime/steamworks-rs" }
